from flask import Flask, render_template, request, flash, redirect, url_for, g, jsonify, abort
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from FDataBase import FDataBase
from UserLogin import UserLogin
from forms import LoginForm
from admin.admin import admin
import os
import sqlite3
from werkzeug.security import generate_password_hash, check_password_hash

DATABASE = '/tmp/siteData.db'
UPLOAD_FOLDER = 'static/images/productImg'

app = Flask(__name__)
app.config.from_object(__name__)
app.config.update(dict(DATABASE=os.path.join(app.root_path, 'siteData.db')))
app.config['SECRET_KEY'] = b'\x87\xd0\xb3\x11\xd4\xea\xd7#\x89\x0f\x06\xedd\x94H\xf8'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['MAX_CONTENT_LENGTH'] = 8 * 1024 * 1024
login_manager = LoginManager(app)
dbase = None
DEBUG = True
app.register_blueprint(admin, url_prefix='/admin')


@login_manager.user_loader
def load_user(user_id):
    print('load_user')
    return UserLogin().fromDB(user_id, dbase)


"""---------DATABASE CONNECTION ---------"""


def connect_db():
    conn = sqlite3.connect(app.config['DATABASE'])
    conn.row_factory = sqlite3.Row
    return conn


def create_db():
    db = connect_db()
    with app.open_resource('sq_db.sql', mode='r') as f:
        db.cursor().executescript(f.read())
    db.commit()
    db.close()


def get_db():
    if not hasattr(g, 'link_db'):
        g.link_db = connect_db()
    return g.link_db


@app.before_request
def before_request():
    global dbase
    db = get_db()
    dbase = FDataBase(db)


@app.teardown_appcontext
def close_db(error):
    if hasattr(g, 'link_db'):
        g.link_db.close()


"""---------DATABASE CLOSE---------"""


# Check if the user is logged in. If true, change the login form to profile
def check_authenticated(name):
    if current_user.is_authenticated:
        name = ['Профиль', 'Выйти', 'profile', 'logout']
        return name
    else:
        return ['Войти', '', 'login', 'login']


# all data use like request.form where default values is dash(-)
data_details = {
    'phone': '-',
    'email': '-',
    'message': '-',
    'name': '-',
    'surname': '-',
    'color': '-',
    'price': '-',
    'viewed': 'viewed-false'}

order_data = {
    'user_id': '-',
    'product_id': '-',
    'product_count': '-',
    'name': '-',
    'phone': '-',
    'mail': '-',
    'secondary_name': '-',
    'secondary_phone': '-',
    'city': '-',
    'street': '-',
    'building_address': '-',
    'entrance': '-',
    'floor': '-',
    'apartment': '-',
    'deliver': '-',
    'deliver_time': '-',
    'note': '-',
    'delivered': 'processing'
}

# list using to put 1 of 3 variables to class \\ default class name is flash
subcategory = ['flash', 'flash success', 'flash error']


@app.route('/')
def index():
    return render_template('index.html',
                           products=dbase.get_products_announce(),
                           check_authenticated=check_authenticated)


@app.route('/state')
def state():
    db = get_db()
    dbase = FDataBase
    return render_template('state.html', menu=dbase.getMenu())


@app.route('/services')
def service():
    return render_template('services.html', check_authenticated=check_authenticated)


@app.route('/product')
def product():
    return render_template('product.html',
                           products=dbase.get_products_announce(),
                           check_authenticated=check_authenticated,
                           title="НАША КОЛЛЕКЦИЯ")


@app.route('/about')
def about():
    return render_template('about.html', check_authenticated=check_authenticated)


@app.route('/contact')
def contact():
    return render_template('contact.html', check_authenticated=check_authenticated)


@app.route('/login', methods=["POST", "GET"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('profile'))
    form = LoginForm
    errors = ''

    if request.method == "POST":
        user = dbase.get_user_by_email(request.form['email'])

        if user and check_password_hash(user['password'], request.form['password']):
            user_login = UserLogin().create(user)
            rm = True if request.form.get('remindme') else False
            login_user(user_login, remember=rm)
            return redirect(url_for('profile'))

        if user is False and request.form['email'] != 'Логин':
            errors += 'Логин имеет неправильный характер'
        if user and check_password_hash(user['password'], request.form['password']) is False:
            errors += 'Пароль имеет неправильный характер'
        if request.form['email'] == 'Логин' or request.form['password'] == 'Пароль':
            errors = 'Вы указали пустое поле ввода  '

        flash(errors, category='error')

    return render_template("login.html", check_authenticated=check_authenticated, form=form)


@app.route('/register', methods=["POST", "GET"])
def register():
    if request.method == "POST":
        if len(request.form["password"]) > 5 and request.form["password"] == request.form["password1"]:
            hash = generate_password_hash(request.form["password"])
            res = dbase.add_user(request.form["name"], request.form["email"], hash, 1000, 'пусто')
            if res:
                flash('Успешная регистрация', category='success')
                return redirect(url_for('login'))
            else:
                flash('error type', category='error')
        else:
            flash('password or name error', category='error')

    return render_template('register.html')


@app.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Вы вышли с аккаунта', category='success')
    return redirect(url_for('login'))


@app.route('/profile')
@login_required
def profile():
    user_id = current_user.get_id()
    user = [current_user.get_id(), current_user.get_name(), current_user.get_cash(), current_user.get_cart()]
    return render_template('profile.html',
                           user=user,
                           get_user_order=dbase.get_user_order(user_id),
                           products=dbase.get_products_announce(),
                           check_authenticated=check_authenticated)


@app.route("/product/<alias>", methods=["POST", "GET"])
def show_product(alias):
    id, name, description, quick_describe, weight, amount, price, imgname = dbase.get_product(alias)
    result_amount = ''
    for i in amount:
        if i != '.':
            result_amount += i
        if i == '.':
            result_amount += i + '<br>'

    result_amount = result_amount[:-4]

    if not name:
        abort(404)

    if request.method == 'POST':
        # Convert user data into a dictionary
        data_get_order = request.form.to_dict(flat=True)
        # Checking what data we get and if string is empty or id doesn't exist convert into dash symbol(-)
        print(data_get_order)
        for i in data_get_order.keys():
            if len(data_get_order[i]) > 0:
                order_data[i] = data_get_order[i]
        res = dbase.order(*tuple(i for i in order_data.values()))
        print(data_get_order, res, order_data)
        if res:
            flash('Данные отправлены', category='success')

        else:
            flash("Непредвиденные обстоятельста, пожалуйста повторите попытку", category='error')

    return render_template('post.html',
                           menu=dbase.get_menu(),
                           post=dbase.get_product(alias),
                           products=dbase.get_products_announce(),
                           result_amount=result_amount,
                           name=name,
                           )


@app.route("/agreement")
def agreement():
    return render_template("agreement.html")


# Checking the information to add to the database from @app.route index
# Processing the data we get
@app.route('/render_user_issue', methods=['POST'])
def render_user_issue():
    # Convert user data into a dictionary
    data_get = request.form.to_dict(flat=True)

    # showing user message if some went wrong or success
    message = ['Что-то пошло не так, отправтьте данные повторно', 'Данные отправлены']
    # Checking what data we get and if string is  empty or id doesn't exist convert into dash symbol(-)
    for i in data_get.keys():
        # if length of data is less than 1 data_details element will get dash symbol(-)
        if len(data_get[i]) > 0:
            data_details[i] = data_get[i]
    # trying to send user data\\ if res not response than res will return false
    res = dbase.add_information(*tuple(i for i in data_details.values()))
    if res:
        return jsonify({'category': subcategory[1], 'content': message[1]})

    return jsonify({'category': subcategory[2], 'content': message[0]})


@app.route('/user_purchase', methods=["POST", "GET"])
def user_purchase():
    message = ['Что-то пошло не так, повторите попытку', 'Заказ принят']
    data_get = request.form.to_dict(flat=True)
    user_id = {'user_id': current_user.get_id()}
    data_get = user_id | data_get

    if data_get:
        for i in data_get.keys():
            # if length of data is less than 1 order_data element will get dash symbol(-)
            if data_get[i] is not None and len(data_get[i]) > 0:
                order_data[i] = data_get[i]
            # trying to send user data\\ if res not response than res will return false
        res = dbase.user_order(*tuple(i for i in order_data.values()))
        if res:
            return jsonify({'category': subcategory[1], 'content': message[1]})
    return jsonify({'category': subcategory[2], 'content': message[0]})


@app.errorhandler(404)
def page_not_found(error):
    return render_template("error.html",
                           products=dbase.get_products_announce(),
                           check_authenticated=check_authenticated)


@app.route("/icons")
def icons():
    icons = ["icon-home",
             "icon-home2",
             "icon-home3",
             "icon-home4",
             "icon-home5",
             "icon-home6",
             "icon-home7",
             "icon-home8",
             "icon-home9",
             "icon-office",
             "icon-city",
             "icon-newspaper",
             "icon-magazine",
             "icon-design",
             "icon-pencil",
             "icon-pencil2",
             "icon-pencil3",
             "icon-pencil4",
             "icon-pencil5",
             "icon-pencil6",
             "icon-pencil7",
             "icon-eraser",
             "icon-eraser2",
             "icon-eraser3",
             "icon-quill",
             "icon-quill2",
             "icon-quill3",
             "icon-quill4",
             "icon-pen",
             "icon-pen-plus",
             "icon-pen-minus",
             "icon-pen2",
             "icon-pen3",
             "icon-pen4",
             "icon-pen5",
             "icon-marker",
             "icon-marker2",
             "icon-blog",
             "icon-blog2",
             "icon-pen6",
             "icon-brush",
             "icon-spray",
             "icon-palette",
             "icon-palette2",
             "icon-color-sampler",
             "icon-toggle",
             "icon-bucket",
             "icon-bucket2",
             "icon-gradient",
             "icon-eyedropper",
             "icon-eyedropper2",
             "icon-eyedropper3",
             "icon-droplet",
             "icon-droplet2",
             "icon-droplet-contrast",
             "icon-color-clear",
             "icon-paint-format",
             "icon-stamp",
             "icon-images",
             "icon-image",
             "icon-image2",
             "icon-image-compare",
             "icon-images2",
             "icon-image3",
             "icon-images3",
             "icon-image4",
             "icon-image5",
             "icon-image6",
             "icon-camera",
             "icon-camera2",
             "icon-camera3",
             "icon-shutter",
             "icon-headphones",
             "icon-headset",
             "icon-music",
             "icon-music2",
             "icon-music3",
             "icon-music4",
             "icon-music5",
             "icon-music6",
             "icon-album",
             "icon-cassette",
             "icon-tape",
             "icon-piano",
             "icon-guitar",
             "icon-trumpet",
             "icon-speakers",
             "icon-play",
             "icon-play2",
             "icon-clapboard-play",
             "icon-clapboard",
             "icon-media",
             "icon-presentation",
             "icon-movie",
             "icon-film",
             "icon-film2",
             "icon-film3",
             "icon-film4",
             "icon-video-camera",
             "icon-video-camera2",
             "icon-video-camera-slash",
             "icon-video-camera3",
             "icon-video-camera4",
             "icon-video-camera-slash2",
             "icon-video-camera5",
             "icon-recording",
             "icon-dice",
             "icon-gamepad",
             "icon-gamepad2",
             "icon-gamepad3",
             "icon-pacman",
             "icon-spades",
             "icon-clubs",
             "icon-diamonds",
             "icon-chess-king",
             "icon-chess-queen",
             "icon-chess-rook",
             "icon-chess-bishop",
             "icon-chess-knight",
             "icon-chess-pawn",
             "icon-chess",
             "icon-bullhorn",
             "icon-megaphone",
             "icon-new",
             "icon-connection",
             "icon-connection2",
             "icon-connection3",
             "icon-connection4",
             "icon-podcast",
             "icon-station",
             "icon-station2",
             "icon-antenna",
             "icon-satellite-dish",
             "icon-satellite-dish2",
             "icon-feed",
             "icon-podcast2",
             "icon-antenna2",
             "icon-mic",
             "icon-mic-off",
             "icon-mic2",
             "icon-mic-off2",
             "icon-mic3",
             "icon-mic4",
             "icon-mic5",
             "icon-book",
             "icon-book2",
             "icon-book-play",
             "icon-book3",
             "icon-bookmark",
             "icon-books",
             "icon-archive",
             "icon-reading",
             "icon-library",
             "icon-library2",
             "icon-graduation",
             "icon-file-text",
             "icon-profile",
             "icon-file-empty",
             "icon-file-empty2",
             "icon-files-empty",
             "icon-files-empty2",
             "icon-file-plus",
             "icon-file-plus2",
             "icon-file-minus",
             "icon-file-minus2",
             "icon-file-download",
             "icon-file-download2",
             "icon-file-upload",
             "icon-file-upload2",
             "icon-file-check",
             "icon-file-check2",
             "icon-file-eye",
             "icon-file-eye2",
             "icon-file-text2",
             "icon-file-text3",
             "icon-file-picture",
             "icon-file-picture2",
             "icon-file-music",
             "icon-file-music2",
             "icon-file-play",
             "icon-file-play2",
             "icon-file-video",
             "icon-file-video2",
             "icon-copy",
             "icon-copy2",
             "icon-file-zip",
             "icon-file-zip2",
             "icon-file-xml",
             "icon-file-xml2",
             "icon-file-css",
             "icon-file-css2",
             "icon-file-presentation",
             "icon-file-presentation2",
             "icon-file-stats",
             "icon-file-stats2",
             "icon-file-locked",
             "icon-file-locked2",
             "icon-file-spreadsheet",
             "icon-file-spreadsheet2",
             "icon-copy3",
             "icon-copy4",
             "icon-paste",
             "icon-paste2",
             "icon-paste3",
             "icon-paste4",
             "icon-stack",
             "icon-stack2",
             "icon-stack3",
             "icon-folder",
             "icon-folder-search",
             "icon-folder-download",
             "icon-folder-upload",
             "icon-folder-plus",
             "icon-folder-plus2",
             "icon-folder-minus",
             "icon-folder-minus2",
             "icon-folder-check",
             "icon-folder-heart",
             "icon-folder-remove",
             "icon-folder2",
             "icon-folder-open",
             "icon-folder3",
             "icon-folder4",
             "icon-folder-plus3",
             "icon-folder-minus3",
             "icon-folder-plus4",
             "icon-folder-minus4",
             "icon-folder-download2",
             "icon-folder-upload2",
             "icon-folder-download3",
             "icon-folder-upload3",
             "icon-folder5",
             "icon-folder-open2",
             "icon-folder6",
             "icon-folder-open3",
             "icon-certificate",
             "icon-cc",
             "icon-price-tag",
             "icon-price-tag2",
             "icon-price-tags",
             "icon-price-tag3",
             "icon-price-tags2",
             "icon-price-tag4",
             "icon-price-tags3",
             "icon-price-tag5",
             "icon-price-tags4",
             "icon-barcode",
             "icon-barcode2",
             "icon-qrcode",
             "icon-ticket",
             "icon-ticket2",
             "icon-theater",
             "icon-store",
             "icon-store2",
             "icon-cart",
             "icon-cart2",
             "icon-cart3",
             "icon-cart4",
             "icon-cart5",
             "icon-cart-add",
             "icon-cart-add2",
             "icon-cart-remove",
             "icon-basket",
             "icon-bag",
             "icon-bag2",
             "icon-percent",
             "icon-coins",
             "icon-coin-dollar",
             "icon-coin-euro",
             "icon-coin-pound",
             "icon-coin-yen",
             "icon-piggy-bank",
             "icon-wallet",
             "icon-cash",
             "icon-cash2",
             "icon-cash3",
             "icon-cash4",
             "icon-credit-card",
             "icon-credit-card2",
             "icon-calculator",
             "icon-calculator2",
             "icon-calculator3",
             "icon-chip",
             "icon-lifebuoy",
             "icon-phone",
             "icon-phone2",
             "icon-phone-slash",
             "icon-phone-wave",
             "icon-phone-plus",
             "icon-phone-minus",
             "icon-phone-plus2",
             "icon-phone-minus2",
             "icon-phone-incoming",
             "icon-phone-outgoing",
             "icon-phone3",
             "icon-phone-slash2",
             "icon-phone-wave2",
             "icon-phone-hang-up",
             "icon-phone-hang-up2",
             "icon-address-book",
             "icon-address-book2",
             "icon-address-book3",
             "icon-notebook",
             "icon-at-sign",
             "icon-envelop",
             "icon-envelop2",
             "icon-envelop3",
             "icon-envelop4",
             "icon-envelop5",
             "icon-mailbox",
             "icon-pushpin",
             "icon-pushpin2",
             "icon-location",
             "icon-location2",
             "icon-location3",
             "icon-location4",
             "icon-location5",
             "icon-location6",
             "icon-location7",
             "icon-compass",
             "icon-compass2",
             "icon-compass3",
             "icon-compass4",
             "icon-compass5",
             "icon-compass6",
             "icon-map",
             "icon-map2",
             "icon-map3",
             "icon-map4",
             "icon-map5",
             "icon-direction",
             "icon-reset",
             "icon-history",
             "icon-clock",
             "icon-clock2",
             "icon-clock3",
             "icon-clock4",
             "icon-watch",
             "icon-watch2",
             "icon-alarm",
             "icon-alarm-add",
             "icon-alarm-check",
             "icon-alarm-cancel",
             "icon-bell",
             "icon-bell2",
             "icon-bell3",
             "icon-bell-plus",
             "icon-bell-minus",
             "icon-bell-check",
             "icon-bell-cross",
             "icon-stopwatch",
             "icon-calendar",
             "icon-calendar2",
             "icon-calendar3",
             "icon-calendar4",
             "icon-calendar5",
             "icon-calendar-empty",
             "icon-calendar-day",
             "icon-calendar-week",
             "icon-printer",
             "icon-printer2",
             "icon-printer3",
             "icon-printer4",
             "icon-shredder",
             "icon-mouse",
             "icon-mouse2",
             "icon-mouse-left",
             "icon-mouse-right",
             "icon-keyboard",
             "icon-keyboard2",
             "icon-typewriter",
             "icon-display",
             "icon-display2",
             "icon-display3",
             "icon-display4",
             "icon-laptop",
             "icon-mobile",
             "icon-mobile2",
             "icon-tablet",
             "icon-mobile3",
             "icon-tv",
             "icon-radio",
             "icon-cabinet",
             "icon-drawer",
             "icon-drawer2",
             "icon-drawer-out",
             "icon-drawer-in",
             "icon-drawer3",
             "icon-box",
             "icon-box-add",
             "icon-box-remove",
             "icon-download",
             "icon-upload",
             "icon-floppy-disk",
             "icon-floppy-disks",
             "icon-floppy-disks2",
             "icon-floppy-disk2",
             "icon-floppy-disk3",
             "icon-disk",
             "icon-disk2",
             "icon-usb-stick",
             "icon-drive",
             "icon-server",
             "icon-database",
             "icon-database2",
             "icon-database3",
             "icon-database4",
             "icon-database-menu",
             "icon-database-add",
             "icon-database-remove",
             "icon-database-insert",
             "icon-database-export",
             "icon-database-upload",
             "icon-database-refresh",
             "icon-database-diff",
             "icon-database-edit",
             "icon-database-edit2",
             "icon-database-check",
             "icon-database-arrow",
             "icon-database-time",
             "icon-database-time2",
             "icon-undo",
             "icon-redo",
             "icon-rotate-ccw",
             "icon-rotate-cw",
             "icon-rotate-ccw2",
             "icon-rotate-cw2",
             "icon-rotate-ccw3",
             "icon-rotate-cw3",
             "icon-flip-vertical",
             "icon-flip-vertical2",
             "icon-flip-horizontal",
             "icon-flip-horizontal2",
             "icon-flip-vertical3",
             "icon-flip-vertical4",
             "icon-angle",
             "icon-shear",
             "icon-unite",
             "icon-subtract",
             "icon-interset",
             "icon-exclude",
             "icon-align-left",
             "icon-align-center-horizontal",
             "icon-align-right",
             "icon-align-top",
             "icon-align-center-vertical",
             "icon-align-bottom",
             "icon-undo2",
             "icon-redo2",
             "icon-forward",
             "icon-reply",
             "icon-reply-all",
             "icon-bubble",
             "icon-bubbles",
             "icon-bubbles2",
             "icon-bubble2",
             "icon-bubbles3",
             "icon-bubbles4",
             "icon-bubble-notification",
             "icon-bubbles5",
             "icon-bubbles6",
             "icon-bubble3",
             "icon-bubble-dots",
             "icon-bubble-lines",
             "icon-bubble4",
             "icon-bubble-dots2",
             "icon-bubble-lines2",
             "icon-bubble5",
             "icon-bubble6",
             "icon-bubbles7",
             "icon-bubble7",
             "icon-bubbles8",
             "icon-bubble8",
             "icon-bubble-dots3",
             "icon-bubble-lines3",
             "icon-bubble9",
             "icon-bubble-dots4",
             "icon-bubble-lines4",
             "icon-bubbles9",
             "icon-bubbles10",
             "icon-bubble-blocked",
             "icon-bubble-quote",
             "icon-bubble-user",
             "icon-bubble-smiley",
             "icon-bubble-check",
             "icon-bubble-video",
             "icon-bubble-link",
             "icon-bubble-lock",
             "icon-bubble-star",
             "icon-bubble-heart",
             "icon-bubble-paperclip",
             "icon-bubble-cancel",
             "icon-bubble-plus",
             "icon-bubble-minus",
             "icon-bubble-notification2",
             "icon-bubble-left",
             "icon-bubble-right",
             "icon-bubble-first",
             "icon-bubble-last",
             "icon-bubble-reply",
             "icon-bubble-forward",
             "icon-bubble-reply2",
             "icon-bubble-forward2",
             "icon-user",
             "icon-users",
             "icon-user-plus",
             "icon-user-minus",
             "icon-user-cancel",
             "icon-user-block",
             "icon-user-lock",
             "icon-user-check",
             "icon-users2",
             "icon-user2",
             "icon-users3",
             "icon-user-plus2",
             "icon-user-minus2",
             "icon-user-cancel2",
             "icon-user-block2",
             "icon-user-lock2",
             "icon-user-check2",
             "icon-user3",
             "icon-user4",
             "icon-user5",
             "icon-user6",
             "icon-users4",
             "icon-user-tie",
             "icon-user7",
             "icon-users5",
             "icon-collaboration",
             "icon-vcard",
             "icon-hat",
             "icon-bowtie",
             "icon-tie",
             "icon-hanger",
             "icon-tshirt",
             "icon-pants",
             "icon-shorts",
             "icon-sock",
             "icon-laundry",
             "icon-quotes-left",
             "icon-quotes-right",
             "icon-quotes-left2",
             "icon-quotes-right2",
             "icon-hour-glass",
             "icon-hour-glass2",
             "icon-hour-glass3",
             "icon-spinner",
             "icon-spinner2",
             "icon-spinner3",
             "icon-spinner4",
             "icon-spinner5",
             "icon-spinner6",
             "icon-spinner7",
             "icon-spinner8",
             "icon-spinner9",
             "icon-spinner10",
             "icon-spinner11",
             "icon-microscope",
             "icon-binoculars",
             "icon-binoculars2",
             "icon-search",
             "icon-zoom-in",
             "icon-zoom-out",
             "icon-search2",
             "icon-zoom-in2",
             "icon-zoom-out2",
             "icon-search3",
             "icon-search4",
             "icon-zoom-in3",
             "icon-zoom-out3",
             "icon-search5",
             "icon-search6",
             "icon-enlarge",
             "icon-shrink",
             "icon-enlarge2",
             "icon-shrink2",
             "icon-enlarge3",
             "icon-shrink3",
             "icon-enlarge4",
             "icon-shrink4",
             "icon-enlarge5",
             "icon-shrink5",
             "icon-enlarge6",
             "icon-shrink6",
             "icon-enlarge7",
             "icon-shrink7",
             "icon-key",
             "icon-key2",
             "icon-key3",
             "icon-key4",
             "icon-key5",
             "icon-keyhole",
             "icon-lock",
             "icon-lock2",
             "icon-lock3",
             "icon-lock4",
             "icon-unlocked",
             "icon-lock5",
             "icon-unlocked2",
             "icon-safe",
             "icon-wrench",
             "icon-wrench2",
             "icon-wrench3",
             "icon-equalizer",
             "icon-equalizer2",
             "icon-equalizer3",
             "icon-equalizer4",
             "icon-cog",
             "icon-cogs",
             "icon-cog2",
             "icon-cog3",
             "icon-cog4",
             "icon-cog5",
             "icon-cog6",
             "icon-cog7",
             "icon-factory",
             "icon-hammer",
             "icon-hammer-wrench",
             "icon-knife",
             "icon-screwdriver",
             "icon-screwdriver2",
             "icon-magic-wand",
             "icon-magic-wand2",
             "icon-pulse",
             "icon-pulse2",
             "icon-aid-kit",
             "icon-aid-kit2",
             "icon-stethoscope",
             "icon-ambulance",
             "icon-alarm2",
             "icon-pandage",
             "icon-pandage2",
             "icon-bug",
             "icon-bug2",
             "icon-syringe",
             "icon-syringe2",
             "icon-pill",
             "icon-construction",
             "icon-traffic-cone",
             "icon-traffic-lights",
             "icon-pie-chart",
             "icon-pie-chart2",
             "icon-pie-chart3",
             "icon-pie-chart4",
             "icon-pie-chart5",
             "icon-pie-chart6",
             "icon-pie-chart7",
             "icon-stats-dots",
             "icon-stats-bars",
             "icon-pie-chart8",
             "icon-stats-bars2",
             "icon-stats-bars3",
             "icon-stats-bars4",
             "icon-stats-bars5",
             "icon-stats-bars6",
             "icon-chart",
             "icon-stats-growth",
             "icon-stats-decline",
             "icon-stats-growth2",
             "icon-stats-decline2",
             "icon-stairs-up",
             "icon-stairs-down",
             "icon-stairs",
             "icon-stairs2",
             "icon-ladder",
             "icon-rating",
             "icon-rating2",
             "icon-rating3",
             "icon-cake",
             "icon-podium",
             "icon-stars",
             "icon-medal-star",
             "icon-medal",
             "icon-medal2",
             "icon-medal-first",
             "icon-medal-second",
             "icon-medal-third",
             "icon-crown",
             "icon-trophy",
             "icon-trophy2",
             "icon-trophy3",
             "icon-diamond",
             "icon-diamond2",
             "icon-trophy4",
             "icon-gift",
             "icon-gift2",
             "icon-balloon",
             "icon-pipe",
             "icon-mustache",
             "icon-mustache2",
             "icon-glass",
             "icon-glass2",
             "icon-glass3",
             "icon-glass4",
             "icon-bottle",
             "icon-bottle2",
             "icon-bottle3",
             "icon-bottle4",
             "icon-mug",
             "icon-fork-knife",
             "icon-spoon-knife",
             "icon-cook",
             "icon-plate",
             "icon-steak",
             "icon-fish",
             "icon-chicken",
             "icon-hamburger",
             "icon-pizza",
             "icon-cheese",
             "icon-bread",
             "icon-icecream",
             "icon-milk",
             "icon-cup",
             "icon-cup2",
             "icon-coffee-bean",
             "icon-coffee",
             "icon-teapot",
             "icon-leaf",
             "icon-leaf2",
             "icon-apple",
             "icon-grapes",
             "icon-cherry",
             "icon-tree",
             "icon-tree2",
             "icon-tree3",
             "icon-tree4",
             "icon-cactus",
             "icon-mountains",
             "icon-paw",
             "icon-footprint",
             "icon-tent",
             "icon-flower",
             "icon-flower2",
             "icon-rocket",
             "icon-meter",
             "icon-meter2",
             "icon-meter-slow",
             "icon-meter-medium",
             "icon-meter-fast",
             "icon-meter3",
             "icon-hammer2",
             "icon-balance",
             "icon-scale",
             "icon-bomb",
             "icon-fire",
             "icon-fire2",
             "icon-lab",
             "icon-atom",
             "icon-atom2",
             "icon-magnet",
             "icon-magnet2",
             "icon-dumbbell",
             "icon-skull",
             "icon-skull2",
             "icon-lamp",
             "icon-lamp2",
             "icon-lamp3",
             "icon-spotlight",
             "icon-lamp4",
             "icon-lamp5",
             "icon-lamp6",
             "icon-lamp7",
             "icon-lamp8",
             "icon-broom",
             "icon-toiletpaper",
             "icon-bin",
             "icon-bin2",
             "icon-bin3",
             "icon-bin4",
             "icon-bin5",
             "icon-briefcase",
             "icon-briefcase2",
             "icon-briefcase3",
             "icon-airplane",
             "icon-airplane2",
             "icon-airplane3",
             "icon-airplane4",
             "icon-paperplane",
             "icon-car",
             "icon-steering-wheel",
             "icon-car2",
             "icon-gas",
             "icon-bus",
             "icon-truck",
             "icon-bike",
             "icon-road",
             "icon-train",
             "icon-train2",
             "icon-ship",
             "icon-boat",
             "icon-chopper",
             "icon-chopper2",
             "icon-cube",
             "icon-cube2",
             "icon-cube3",
             "icon-cube4",
             "icon-pyramid",
             "icon-pyramid2",
             "icon-package",
             "icon-puzzle",
             "icon-puzzle2",
             "icon-puzzle3",
             "icon-puzzle4",
             "icon-glasses-3d",
             "icon-glasses-3d2",
             "icon-glasses",
             "icon-glasses2",
             "icon-brain",
             "icon-accessibility",
             "icon-accessibility2",
             "icon-strategy",
             "icon-target",
             "icon-target2",
             "icon-target3",
             "icon-ammo",
             "icon-gun",
             "icon-gun-forbidden",
             "icon-shield",
             "icon-shield-check",
             "icon-shield-notice",
             "icon-shield2",
             "icon-shield3",
             "icon-shield4",
             "icon-soccer",
             "icon-football",
             "icon-archery",
             "icon-bow",
             "icon-sword",
             "icon-tennis",
             "icon-pingpong",
             "icon-baseball",
             "icon-basketball",
             "icon-golf",
             "icon-golf2",
             "icon-hockey",
             "icon-racing",
             "icon-finish",
             "icon-eight-ball",
             "icon-bowling",
             "icon-bowling2",
             "icon-power",
             "icon-power2",
             "icon-power3",
             "icon-switch",
             "icon-switch2",
             "icon-power-cord",
             "icon-power-cord2",
             "icon-outlet",
             "icon-clipboard",
             "icon-clipboard2",
             "icon-clipboard3",
             "icon-clipboard4",
             "icon-clipboard5",
             "icon-clipboard6",
             "icon-playlist",
             "icon-playlist-add",
             "icon-list-numbered",
             "icon-list",
             "icon-list2",
             "icon-more",
             "icon-more2",
             "icon-grid",
             "icon-grid2",
             "icon-grid3",
             "icon-grid4",
             "icon-grid5",
             "icon-grid6",
             "icon-grid7",
             "icon-tree5",
             "icon-tree6",
             "icon-tree7",
             "icon-lan",
             "icon-lan2",
             "icon-lan3",
             "icon-menu",
             "icon-circle-small",
             "icon-menu2",
             "icon-menu3",
             "icon-menu4",
             "icon-menu5",
             "icon-menu6",
             "icon-menu7",
             "icon-menu8",
             "icon-menu9",
             "icon-menu10",
             "icon-cloud",
             "icon-cloud-download",
             "icon-cloud-upload",
             "icon-cloud-check",
             "icon-cloud2",
             "icon-cloud-download2",
             "icon-cloud-upload2",
             "icon-cloud-check2",
             "icon-download2",
             "icon-download3",
             "icon-upload2",
             "icon-upload3",
             "icon-import",
             "icon-import2",
             "icon-download4",
             "icon-upload4",
             "icon-download5",
             "icon-upload5",
             "icon-download6",
             "icon-upload6",
             "icon-download7",
             "icon-upload7",
             "icon-download8",
             "icon-upload8",
             "icon-download9",
             "icon-upload9",
             "icon-download10",
             "icon-upload10",
             "icon-sphere",
             "icon-sphere2",
             "icon-sphere3",
             "icon-planet",
             "icon-planet2",
             "icon-earth",
             "icon-earth2",
             "icon-earth3",
             "icon-link",
             "icon-unlink",
             "icon-link2",
             "icon-unlink2",
             "icon-link3",
             "icon-unlink3",
             "icon-link4",
             "icon-unlink4",
             "icon-link5",
             "icon-unlink5",
             "icon-anchor",
             "icon-flag",
             "icon-flag2",
             "icon-flag3",
             "icon-flag4",
             "icon-flag5",
             "icon-flag6",
             "icon-flag7",
             "icon-flag8",
             "icon-attachment",
             "icon-attachment2",
             "icon-eye",
             "icon-eye-plus",
             "icon-eye-minus",
             "icon-eye-blocked",
             "icon-eye2",
             "icon-eye-blocked2",
             "icon-eye3",
             "icon-eye-blocked3",
             "icon-eye4",
             "icon-bookmark2",
             "icon-bookmark3",
             "icon-bookmarks",
             "icon-bookmark4",
             "icon-spotlight2",
             "icon-starburst",
             "icon-snowflake",
             "icon-temperature",
             "icon-temperature2",
             "icon-weather-lightning",
             "icon-weather-lightning2",
             "icon-weather-rain",
             "icon-weather-rain2",
             "icon-weather-snow",
             "icon-weather-snow2",
             "icon-weather-cloud-wind",
             "icon-weather-cloud-wind2",
             "icon-weather-cloud-sun",
             "icon-weather-cloud-sun2",
             "icon-weather-cloudy",
             "icon-weather-cloudy2",
             "icon-weather-sun-wind",
             "icon-weather-sun-wind2",
             "icon-sun",
             "icon-sun2",
             "icon-moon",
             "icon-day-night",
             "icon-day-night2",
             "icon-weather-windy",
             "icon-fan",
             "icon-umbrella",
             "icon-sun3",
             "icon-contrast",
             "icon-brightness-contrast",
             "icon-brightness-high",
             "icon-brightness-medium",
             "icon-brightness-low",
             "icon-bed",
             "icon-bed2",
             "icon-furniture",
             "icon-chair",
             "icon-star-empty",
             "icon-star-empty2",
             "icon-star-full",
             "icon-star-empty3",
             "icon-star-half",
             "icon-star-full2",
             "icon-star",
             "icon-heart",
             "icon-heart2",
             "icon-heart3",
             "icon-heart4",
             "icon-heart-broken",
             "icon-heart5",
             "icon-heart6",
             "icon-heart-broken2",
             "icon-heart7",
             "icon-heart8",
             "icon-heart-broken3",
             "icon-lips",
             "icon-lips2",
             "icon-thumbs-up",
             "icon-thumbs-up2",
             "icon-thumbs-down",
             "icon-thumbs-down2",
             "icon-thumbs-up3",
             "icon-thumbs-down3",
             "icon-height",
             "icon-man",
             "icon-woman",
             "icon-man-woman",
             "icon-male",
             "icon-female",
             "icon-peace",
             "icon-yin-yang",
             "icon-happy",
             "icon-happy2",
             "icon-smile",
             "icon-smile2",
             "icon-tongue",
             "icon-tongue2",
             "icon-sad",
             "icon-sad2",
             "icon-wink",
             "icon-wink2",
             "icon-grin",
             "icon-grin2",
             "icon-cool",
             "icon-cool2",
             "icon-angry",
             "icon-angry2",
             "icon-evil",
             "icon-evil2",
             "icon-shocked",
             "icon-shocked2",
             "icon-baffled",
             "icon-baffled2",
             "icon-confused",
             "icon-confused2",
             "icon-neutral",
             "icon-neutral2",
             "icon-hipster",
             "icon-hipster2",
             "icon-wondering",
             "icon-wondering2",
             "icon-sleepy",
             "icon-sleepy2",
             "icon-frustrated",
             "icon-frustrated2",
             "icon-crying",
             "icon-crying2",
             "icon-cursor",
             "icon-cursor2",
             "icon-lasso",
             "icon-lasso2",
             "icon-select",
             "icon-select2",
             "icon-point-up",
             "icon-point-right",
             "icon-point-down",
             "icon-point-left",
             "icon-pointer",
             "icon-reminder",
             "icon-drag-left-right",
             "icon-drag-left",
             "icon-drag-right",
             "icon-touch",
             "icon-multitouch",
             "icon-touch-zoom",
             "icon-touch-pinch",
             "icon-hand",
             "icon-grab",
             "icon-stack-empty",
             "icon-stack-plus",
             "icon-stack-minus",
             "icon-stack-star",
             "icon-stack-picture",
             "icon-stack-down",
             "icon-stack-up",
             "icon-stack-cancel",
             "icon-stack-check",
             "icon-stack-text",
             "icon-stack-clubs",
             "icon-stack-spades",
             "icon-stack-hearts",
             "icon-stack-diamonds",
             "icon-stack-user",
             "icon-stack4",
             "icon-stack-music",
             "icon-stack-play",
             "icon-move",
             "icon-dots",
             "icon-warning",
             "icon-warning2",
             "icon-notification",
             "icon-notification2",
             "icon-question",
             "icon-question2",
             "icon-question3",
             "icon-question4",
             "icon-question5",
             "icon-question6",
             "icon-plus",
             "icon-minus",
             "icon-plus2",
             "icon-minus2",
             "icon-plus3",
             "icon-minus3",
             "icon-plus-circle",
             "icon-minus-circle",
             "icon-plus-circle2",
             "icon-minus-circle2",
             "icon-info",
             "icon-info2",
             "icon-cancel-circle",
             "icon-cancel-circle2",
             "icon-blocked",
             "icon-cancel-square",
             "icon-cancel-square2",
             "icon-cancel",
             "icon-spam",
             "icon-cross",
             "icon-cross2",
             "icon-cross3",
             "icon-checkmark",
             "icon-checkmark2",
             "icon-checkmark3",
             "icon-checkmark4",
             "icon-checkmark5",
             "icon-spell-check",
             "icon-spell-check2",
             "icon-enter",
             "icon-exit",
             "icon-enter2",
             "icon-exit2",
             "icon-enter3",
             "icon-exit3",
             "icon-wall",
             "icon-fence",
             "icon-play3",
             "icon-pause",
             "icon-stop",
             "icon-previous",
             "icon-next",
             "icon-backward",
             "icon-forward2",
             "icon-play4",
             "icon-pause2",
             "icon-stop2",
             "icon-backward2",
             "icon-forward3",
             "icon-first",
             "icon-last",
             "icon-previous2",
             "icon-next2",
             "icon-eject",
             "icon-volume-high",
             "icon-volume-medium",
             "icon-volume-low",
             "icon-volume-mute",
             "icon-speaker-left",
             "icon-speaker-right",
             "icon-volume-mute2",
             "icon-volume-increase",
             "icon-volume-decrease",
             "icon-volume-high2",
             "icon-volume-medium2",
             "icon-volume-medium3",
             "icon-volume-low2",
             "icon-volume-mute3",
             "icon-volume-increase2",
             "icon-volume-decrease2",
             "icon-volume-decrease3",
             "icon-volume-5",
             "icon-volume-4",
             "icon-volume-3",
             "icon-volume-2",
             "icon-volume-1",
             "icon-volume-0",
             "icon-volume-mute4",
             "icon-volume-mute5",
             "icon-loop",
             "icon-loop2",
             "icon-loop3",
             "icon-infinite-square",
             "icon-infinite",
             "icon-infinite2",
             "icon-loop4",
             "icon-shuffle",
             "icon-shuffle2",
             "icon-wave",
             "icon-wave2",
             "icon-split",
             "icon-merge",
             "icon-first2",
             "icon-last2",
             "icon-arrow-up",
             "icon-arrow-up2",
             "icon-arrow-up3",
             "icon-arrow-up4",
             "icon-arrow-right",
             "icon-arrow-right2",
             "icon-arrow-right3",
             "icon-arrow-right4",
             "icon-arrow-down",
             "icon-arrow-down2",
             "icon-arrow-down3",
             "icon-arrow-down4",
             "icon-arrow-left",
             "icon-arrow-left2",
             "icon-arrow-left3",
             "icon-arrow-left4",
             "icon-arrow-up5",
             "icon-arrow-right5",
             "icon-arrow-down5",
             "icon-arrow-left5",
             "icon-arrow-up-left",
             "icon-arrow-up6",
             "icon-arrow-up-right",
             "icon-arrow-right6",
             "icon-arrow-down-right",
             "icon-arrow-down6",
             "icon-arrow-down-left",
             "icon-arrow-left6",
             "icon-arrow-up-left2",
             "icon-arrow-up7",
             "icon-arrow-up-right2",
             "icon-arrow-right7",
             "icon-arrow-down-right2",
             "icon-arrow-down7",
             "icon-arrow-down-left2",
             "icon-arrow-left7",
             "icon-arrow-up-left3",
             "icon-arrow-up8",
             "icon-arrow-up-right3",
             "icon-arrow-right8",
             "icon-arrow-down-right3",
             "icon-arrow-down8",
             "icon-arrow-down-left3",
             "icon-arrow-left8",
             "icon-circle-up",
             "icon-circle-right",
             "icon-circle-down",
             "icon-circle-left",
             "icon-circle-up2",
             "icon-circle-right2",
             "icon-circle-down2",
             "icon-circle-left2",
             "icon-circle-up-left",
             "icon-circle-up3",
             "icon-circle-up-right",
             "icon-circle-right3",
             "icon-circle-down-right",
             "icon-circle-down3",
             "icon-circle-down-left",
             "icon-circle-left3",
             "icon-circle-up-left2",
             "icon-circle-up4",
             "icon-circle-up-right2",
             "icon-circle-right4",
             "icon-circle-down-right2",
             "icon-circle-down4",
             "icon-circle-down-left2",
             "icon-circle-left4",
             "icon-arrow-resize",
             "icon-arrow-resize2",
             "icon-arrow-resize3",
             "icon-arrow-resize4",
             "icon-arrow-resize5",
             "icon-arrow-resize6",
             "icon-arrow-resize7",
             "icon-arrow-resize8",
             "icon-square-up-left",
             "icon-square-up",
             "icon-square-up-right",
             "icon-square-right",
             "icon-square-down-right",
             "icon-square-down",
             "icon-square-down-left",
             "icon-square-left",
             "icon-arrow-up9",
             "icon-arrow-right9",
             "icon-arrow-down9",
             "icon-arrow-left9",
             "icon-arrow-up10",
             "icon-arrow-right10",
             "icon-arrow-down10",
             "icon-arrow-left10",
             "icon-arrow-up-left4",
             "icon-arrow-up11",
             "icon-arrow-up-right4",
             "icon-arrow-right11",
             "icon-arrow-down-right4",
             "icon-arrow-down11",
             "icon-arrow-down-left4",
             "icon-arrow-left11",
             "icon-arrow-up-left5",
             "icon-arrow-up12",
             "icon-arrow-up-right5",
             "icon-arrow-right12",
             "icon-arrow-down-right5",
             "icon-arrow-down12",
             "icon-arrow-down-left5",
             "icon-arrow-left12",
             "icon-arrow-up13",
             "icon-arrow-right13",
             "icon-arrow-down13",
             "icon-arrow-left13",
             "icon-arrow-up14",
             "icon-arrow-right14",
             "icon-arrow-down14",
             "icon-arrow-left14",
             "icon-circle-up5",
             "icon-circle-right5",
             "icon-circle-down5",
             "icon-circle-left5",
             "icon-circle-up6",
             "icon-circle-right6",
             "icon-circle-down6",
             "icon-circle-left6",
             "icon-arrow-up15",
             "icon-arrow-right15",
             "icon-arrow-down15",
             "icon-arrow-left15",
             "icon-arrow-up16",
             "icon-arrow-right16",
             "icon-arrow-down16",
             "icon-arrow-left16",
             "icon-menu-open",
             "icon-menu-open2",
             "icon-menu-close",
             "icon-menu-close2",
             "icon-enter4",
             "icon-enter5",
             "icon-esc",
             "icon-enter6",
             "icon-backspace",
             "icon-backspace2",
             "icon-tab",
             "icon-transmission",
             "icon-transmission2",
             "icon-sort",
             "icon-sort2",
             "icon-move-up",
             "icon-move-down",
             "icon-sort-alpha-asc",
             "icon-sort-alpha-desc",
             "icon-sort-numeric-asc",
             "icon-sort-numberic-desc",
             "icon-sort-amount-asc",
             "icon-sort-amount-desc",
             "icon-sort-time-asc",
             "icon-sort-time-desc",
             "icon-battery-6",
             "icon-battery-5",
             "icon-battery-4",
             "icon-battery-3",
             "icon-battery-2",
             "icon-battery-1",
             "icon-battery-0",
             "icon-battery-charging",
             "icon-key-keyboard",
             "icon-key-A",
             "icon-key-up",
             "icon-key-right",
             "icon-key-down",
             "icon-key-left",
             "icon-command",
             "icon-shift",
             "icon-ctrl",
             "icon-opt",
             "icon-checkbox-checked",
             "icon-checkbox-unchecked",
             "icon-checkbox-partial",
             "icon-square",
             "icon-triangle",
             "icon-triangle2",
             "icon-diamond3",
             "icon-diamond4",
             "icon-checkbox-checked2",
             "icon-checkbox-unchecked2",
             "icon-checkbox-partial2",
             "icon-radio-checked",
             "icon-radio-checked2",
             "icon-radio-unchecked",
             "icon-toggle-on",
             "icon-toggle-off",
             "icon-checkmark-circle",
             "icon-circle",
             "icon-circle2",
             "icon-circles",
             "icon-circles2",
             "icon-crop",
             "icon-crop2",
             "icon-make-group",
             "icon-ungroup",
             "icon-vector",
             "icon-vector2",
             "icon-rulers",
             "icon-ruler",
             "icon-pencil-ruler",
             "icon-scissors",
             "icon-scissors2",
             "icon-scissors3",
             "icon-haircut",
             "icon-comb",
             "icon-filter",
             "icon-filter2",
             "icon-filter3",
             "icon-filter4",
             "icon-font",
             "icon-ampersand",
             "icon-ligature",
             "icon-ligature2",
             "icon-font-size",
             "icon-typography",
             "icon-text-height",
             "icon-text-width",
             "icon-height2",
             "icon-width",
             "icon-bold",
             "icon-underline",
             "icon-italic",
             "icon-strikethrough",
             "icon-strikethrough2",
             "icon-font-size2",
             "icon-bold2",
             "icon-underline2",
             "icon-italic2",
             "icon-strikethrough3",
             "icon-omega",
             "icon-sigma",
             "icon-nbsp",
             "icon-page-break",
             "icon-page-break2",
             "icon-superscript",
             "icon-subscript",
             "icon-superscript2",
             "icon-subscript2",
             "icon-text-color",
             "icon-highlight",
             "icon-pagebreak",
             "icon-clear-formatting",
             "icon-table",
             "icon-table2",
             "icon-insert-template",
             "icon-pilcrow",
             "icon-ltr",
             "icon-rtl",
             "icon-ltr2",
             "icon-rtl2",
             "icon-section",
             "icon-paragraph-left",
             "icon-paragraph-center",
             "icon-paragraph-right",
             "icon-paragraph-justify",
             "icon-paragraph-left2",
             "icon-paragraph-center2",
             "icon-paragraph-right2",
             "icon-paragraph-justify2",
             "icon-indent-increase",
             "icon-indent-decrease",
             "icon-paragraph-left3",
             "icon-paragraph-center3",
             "icon-paragraph-right3",
             "icon-paragraph-justify3",
             "icon-indent-increase2",
             "icon-indent-decrease2",
             "icon-share",
             "icon-share2",
             "icon-new-tab",
             "icon-new-tab2",
             "icon-popout",
             "icon-embed",
             "icon-embed2",
             "icon-markup",
             "icon-regexp",
             "icon-regexp2",
             "icon-code",
             "icon-circle-css",
             "icon-circle-code",
             "icon-terminal",
             "icon-unicode",
             "icon-seven-segment-0",
             "icon-seven-segment-1",
             "icon-seven-segment-2",
             "icon-seven-segment-3",
             "icon-seven-segment-4",
             "icon-seven-segment-5",
             "icon-seven-segment-6",
             "icon-seven-segment-7",
             "icon-seven-segment-8",
             "icon-seven-segment-9",
             "icon-share3",
             "icon-share4",
             "icon-mail",
             "icon-mail2",
             "icon-mail3",
             "icon-mail4",
             "icon-amazon",
             "icon-google",
             "icon-google2",
             "icon-google3",
             "icon-google-plus",
             "icon-google-plus2",
             "icon-google-plus3",
             "icon-hangouts",
             "icon-google-drive",
             "icon-facebook",
             "icon-facebook2",
             "icon-instagram",
             "icon-whatsapp",
             "icon-spotify",
             "icon-telegram",
             "icon-twitter",
             "icon-vine",
             "icon-vk",
             "icon-renren",
             "icon-sina-weibo",
             "icon-rss",
             "icon-rss2",
             "icon-youtube",
             "icon-youtube2",
             "icon-twitch",
             "icon-vimeo",
             "icon-vimeo2",
             "icon-lanyrd",
             "icon-flickr",
             "icon-flickr2",
             "icon-flickr3",
             "icon-flickr4",
             "icon-dribbble",
             "icon-behance",
             "icon-behance2",
             "icon-deviantart",
             "icon-500px",
             "icon-steam",
             "icon-steam2",
             "icon-dropbox",
             "icon-onedrive",
             "icon-github",
             "icon-npm",
             "icon-basecamp",
             "icon-trello",
             "icon-wordpress",
             "icon-joomla",
             "icon-ello",
             "icon-blogger",
             "icon-blogger2",
             "icon-tumblr",
             "icon-tumblr2",
             "icon-yahoo",
             "icon-yahoo2",
             "icon-tux",
             "icon-appleinc",
             "icon-finder",
             "icon-android",
             "icon-windows",
             "icon-windows8",
             "icon-soundcloud",
             "icon-soundcloud2",
             "icon-skype",
             "icon-reddit",
             "icon-hackernews",
             "icon-wikipedia",
             "icon-linkedin",
             "icon-linkedin2",
             "icon-lastfm",
             "icon-lastfm2",
             "icon-delicious",
             "icon-stumbleupon",
             "icon-stumbleupon2",
             "icon-stackoverflow",
             "icon-pinterest",
             "icon-pinterest2",
             "icon-xing",
             "icon-xing2",
             "icon-flattr",
             "icon-foursquare",
             "icon-yelp",
             "icon-paypal",
             "icon-chrome",
             "icon-firefox",
             "icon-IE",
             "icon-edge",
             "icon-safari",
             "icon-opera",
             "icon-file-pdf",
             "icon-file-openoffice",
             "icon-file-word",
             "icon-file-excel",
             "icon-libreoffice",
             "icon-html-five",
             "icon-html-five2",
             "icon-css3",
             "icon-git",
             "icon-codepen",
             "icon-svg",
             "icon-IcoMoon"]
    return render_template("icon.html", icons=icons)


if __name__ == '__main__':
    app.run(debug=True)
